-- user: id, username, real name, location
-- posts: id, posts_ids, user_id, post_time
-- likes: id, user_id, post_id
-- comments: id, user_id, post_id
-- followers: id, user_id, followers_id, followed_id
